### ISSUE TITLE
Can't get probot/@octokit/rest/plugin-rest-endpoint-methods to compile

### ISSUE THREAD

**Issue by bcoe** [octokit/rest.js#45]
There seems to be an incompatibility between `@octokit/rest`, `probot`, and `plugin-rest-endpoint-methods`, such that I cannot get the modules to compile together:

```
node_modules/@octokit/rest/node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:1801:60 - error TS2339: Property 'POST /repos/{owner}/{repo}/forks{?org,organization}' does not exist on type 'Endpoints'.

1801             parameters: RequestParameters & Omit<Endpoints["POST /repos/{owner}/{repo}/forks{?org,organization}"]["parameters"], "baseUrl" | "headers" | "mediaType">;
                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@octokit/rest/node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:1802:33 - error TS2339: Property 'POST /repos/{owner}/{repo}/forks{?org,organization}' does not exist on type 'Endpoints'.

1802             response: Endpoints["POST /repos/{owner}/{repo}/forks{?org,organization}"]["response"];
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/probot/node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:1801:60 - error TS2339: Property 'POST /repos/{owner}/{repo}/forks{?org,organization}' does not exist on type 'Endpoints'.

1801             parameters: RequestParameters & Omit<Endpoints["POST /repos/{owner}/{repo}/forks{?org,organization}"]["parameters"], "baseUrl" | "headers" | "mediaType">;
                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/probot/node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:1802:33 - error TS2339: Property 'POST /repos/{owner}/{repo}/forks{?org,organization}' does not exist on type 'Endpoints'.

1802             response: Endpoints["POST /repos/{owner}/{repo}/forks{?org,organization}"]["response"];
```

I can't seem to figure out an approach to make them play nice together.

Refs: https://github.com/googleapis/repo-automation-bots/pull/1660

**Comment by gr2m** [comment]
`@ocotkit/rest` needs to be updated, somehow the automation failed me on this, I'm fixing it now.

**Comment by gr2m** [comment]
incoming: https://github.com/octokit/rest.js/pull/46

The problem here is that strictly speaking the [change @el7cosmos mentioned above](https://github.com/octokit/types.ts/pull/297/files?file-filters%5B%5D=.ts#diff-6e34f3ccc1fd41b44cec74317606475053c89f3ffe0133356443861f5e7f1150L4361) is a breaking change. But it was a bug that was introduced by accident, and the friction to create a breaking version just because of this outweights the alternative by an order of magnitude.

The problem is that theversion of `@octokit/types` is not pinned, so you get the latest version when you do a fresh install of `@octokit/rest`. The version of `@octokit/plugin-rest-api-endpoints` on the other hand is pinned, so unless you update to the latest version of `@octokit/rest` (coming in a minute) you will see the above error.

Because it's a build error for typescript users only, not a problem you'd see in production, we don't consider it a breaking change.

**Comment by gr2m** [comment]
can you confirm that the problem is resolved for you?

**Comment by el7cosmos** [comment]
@gr2m thanks for the quick response, I can't confirm resolution as my problem lies in `@actions/github` that depends on `@octokit/plugin-rest-endpoint-methods: ^4.0.0` so I can't update to `^5`

**Comment by gr2m** [comment]
> my problem lies in `@actions/github`

I do not maintain that package and can't help with that I'm afraid

**Comment by bcoe** [comment]
@gr2m this seems to have addressed the `@octokit/rest` issue 🎉 , but I'm still getting a compiler issue for `probot@11.2.0`.

If I delete probot's dependency ` rm -rf node_modules/probot/node_modules/@octokit/plugin-rest-endpoint-methods`, then I am able to compile, however I seem to have some slight unrelated errors in unit tests:

```
    TypeError: Cannot read property 'listComments' of undefined
        at Object.addOrUpdateIssueComment (/Users/bencoe/google/repo-automation-bots/packages/gcf-utils/build/src/gcf-utils.js:58:54)
            -> /Users/bencoe/google/repo-automation-bots/packages/gcf-utils/src/gcf-utils.ts:102:52
        at /Users/bencoe/google/repo-automation-bots/packages/gcf-utils/build/test/gcf-utils.js:31:27
            -> /Users/bencoe/google/repo-automation-bots/packages/gcf-utils/test/gcf-utils.ts:32:11
        at /Users/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/@octokit/webhooks/dist-node/index.j
        ```

**Comment by gr2m** [comment]
can you create a separate issue for that in Probot? I'm not sure where the problem could lie. I'm surprised to see `@octokit/webhooks` in the error stack

**Comment by bcoe** [comment]
@gr2m I think that I see the issue actually, I should be calling `octokit.rest.list` now right?

**Comment by bcoe** [comment]
so the actual outstanding issue is just that `probot` seems to be pinned to an old `plugin-rest-endpoint-methods`.

**Comment by el7cosmos** [comment]
Thank you @gr2m for rolling out `4.x`. Problem solve after updating `@octokit/plugin-rest-endpoint-methods` to `4.15.1`
